version = 0.1
[default.deploy.parameters]
stack_name = "sibyl-kb-layer"
resolve_s3 = true
s3_prefix = "sibyl-kb-layer"
region = "us-east-1"
profile = "admin"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
